server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    #账号配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiongmao?serverTimezone=Asia/Shanghai
    username: root
    password: zjx19950426.
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 1000
#      test-on-borrow: true
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 10.175.24.207
    username: itzjx
    password: itzjx
    virtual-host: /itzjx
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: xm.item.exchange
    publisher-confirm-type: correlated
  redis:
    host: 192.168.1.100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5  #指示从eureka服务器获取注册表信息的频率
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.itzjx.order.pojo

xm:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: /home/zhaojiexiong/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 5000
    httpReadTimeoutMs: 10000
    notifyUrl: http://www.itzjx.com/