server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.175.24.207:9300
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 10.175.24.207
    username: itzjx
    password: itzjx
    virtual-host: /itzjx
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

