server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    #账号配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiongmao?serverTimezone=Asia/Shanghai
    username: root
    password: zjx19950426.
  rabbitmq:
    host: 10.175.24.207
    username: itzjx
    password: itzjx
    virtual-host: /itzjx
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: xm.item.exchange
    publisher-confirm-type: correlated
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

#output sql select
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
