server:
  port: 10086

spring:
  application:
    name: xm-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    register-with-eureka: false
    fetch-registry: false
    instance-id: xiongmao
    prefer-ip-address: true
