server:
  port: 8888

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
xm:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: /home/zhaojiexiong/rsa/rsa.pub # 生成公钥的地址
    priKeyPath: /home/zhaojiexiong/rsa/rsa.pri # 生成私钥的地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 1800   #cookie过期时间 ，单位秒